server:
  port: 8082
  max-http-header-size: 102400
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 955099 #改成自己数据库的密码
    url: jdbc:mysql://127.0.0.1:3306/hospital_management?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
  resources:
    static-locations: classpath:/resources/
mybatis:
  mapper-locations: classpath:mapper/*.xml